### ISSUE TITLE
Activate discussion tab in your project

### ISSUE THREAD

**Issue by mars3142** [FilledStacks/boxtout#4]
On github there is a new feature for discussions, which can be activated in the [settings](https://github.com/FilledStacks/boxtout/settings) of your project. The discussions can also be grouped into different categories, so it will not spam the issues area.

**Comment by FilledStacks** [comment]
Aaaaaaaaaah! You see. This is why I collaboration works well 😄 I had no idea. I'm turning that on now and updating the issue.

**Comment by FilledStacks** [comment]
Much appreciated. The latest discussion can be found [here](https://github.com/FilledStacks/boxtout/discussions/5)
