### ISSUE TITLE
Update term for http function from idle to restful

### ISSUE THREAD

**Issue by FilledStacks** [FilledStacks/boxtout#8]
As pointed out in [this reply](https://github.com/FilledStacks/boxtout/discussions/7#discussioncomment-347807) from Llewellyn. Instead of using **idle** for the http function group name, we should use the industry standard and call it restful. 

This issue is created as the task to update the naming in the documentation as well as in the code

- [x] Update the term idle to restful in the written documentation
- [x] Update the term idle to restful in the codebase

If you'd like to do this please comment below. I'll only get around to this on Thursday

**Comment by llewellyncollins** [comment]
I don't want to make more work for you =P. I will pick this up

**Comment by FilledStacks** [comment]
haha thanks! @llewellyncollins

**Comment by llewellyncollins** [comment]
I have created a PR for this change. But it looks like I cannot 1) assign this issue to myself 2) add reviewers to my PR

**Comment by FilledStacks** [comment]
Updated the Wiki reference to Idle function as well. This ticket is donezo!
